USE vehicleHouse;

-- Queries
-- GET ALL DEALERSHIPS 
SELECT * FROM DEALERSHIPS;

-- FIND ALL VEHICLES FOR A SPECIFIC DEALERSHIP
SELECT D.DEALERSHIP_ID
	, D.NAME
	, V.VIN 
	,V.MAKE
	, V.TYPE
	, V.YEAR
	, V.COLOR
	, V.ODOMETER
FROM DEALERSHIPS AS D
JOIN INVENTORY AS I 
ON I.DEALERSHIP_ID = D.DEALERSHIP_ID
JOIN VEHICLES AS V
ON I.VIN = V.VIN
WHERE D.NAME = 'Tokyo-Car-House';

-- FIND A CAR BY VIN
SELECT * FROM VEHICLES 
WHERE VIN = 3;

-- FIND THE DEALERSHIP WHERE A CERTAIN CAR IS LOCATED, BY VIN
SELECT D.DEALERSHIP_ID
		, D.NAME 
		,D.ADDRESS
		, D.PHONE
FROM DEALERSHIPS AS D
JOIN INVENTORY AS I
ON D.DEALERSHIP_ID = I.DEALERSHIP_ID
WHERE I.VIN = 3;

-- FIND ALL DEALERSHIPS THAT HAVE A CERTAIN CAR TYPE (SEDAN)
SELECT D.DEALERSHIP_ID, D.NAME ,D.ADDRESS, D.PHONE
FROM DEALERSHIPS AS D
JOIN INVENTORY AS I
ON D.DEALERSHIP_ID = I.DEALERSHIP_ID
JOIN VEHICLES AS V
ON I.VIN = V.VIN
WHERE V.TYPE = 'SEDAN';

-- GET ALL SALES INFORMATION FOR A SPECIFIC DEALER FOR A SPECIFIC DATE RANGE (SALES CONTRACT)
SELECT D.DEALERSHIP_ID, D.NAME ,D.ADDRESS, D.PHONE, V.SOLD
FROM DEALERSHIPS AS D
JOIN INVENTORY AS I
ON D.DEALERSHIP_ID = I.DEALERSHIP_ID
JOIN VEHICLES AS V
ON I.VIN = V.VIN
JOIN SALES_CONTRACTS AS S
ON S.VIN = I.VIN
WHERE S.DATE BETWEEN '2023-06-03' AND '2023-06-05';

-- GET ALL SALES INFORMATION FOR A SPECIFIC DEALER FOR A SPECIFIC DATE RANGE (LEASE CONTRACTS)
SELECT D.DEALERSHIP_ID, D.NAME ,D.ADDRESS, D.PHONE, V.SOLD
FROM DEALERSHIPS AS D
JOIN INVENTORY AS I
ON D.DEALERSHIP_ID = I.DEALERSHIP_ID
JOIN VEHICLES AS V
ON I.VIN = V.VIN
JOIN LEASE_CONTRACTS AS L
ON L.VIN = I.VIN
WHERE L.DATE BETWEEN '2023-06-03' AND '2023-06-05';